### ISSUE TITLE
Implement remote control platform

### ISSUE THREAD

**Issue by Drafteed** [dcnielsen90/python-bravia-tv#16]
Hello! 
Can you implement [remote control platform for HA](https://www.home-assistant.io/integrations/remote/) for sending remote keys?
Such as: [this](https://github.com/custom-components/media_player.braviatv_psk#braviatv_pskbravia_command) or like [this](https://github.com/home-assistant/core/pull/47249).

**Comment by dcnielsen90** [comment]
This is definitely doable. It's 100% a feature add in Home Assistant. This library has all it needs to do this as is. (Send_command)

**Comment by Drafteed** [comment]
> This is definitely doable. It's 100% a feature add in Home Assistant. This library has all it needs to do this as is. (Send_command)

I know :) I have already started developing this feature. And I have already made [a first working version](https://github.com/Drafteed/core/blob/braviatv-remote/homeassistant/components/braviatv/remote.py). But in the current implementation I don't like one thing: additional polling to get the is_on state. 

There are two ways to solve this problem here:
1. Store in `BraviaRC` current (last) power state value in property to use it in `is_on` (call methods not allowed here). This needs to be done in your repo. 
2. Refactor `media_player` to use an additional wrapper class that will be initialized to `__init__.py` and shared between several platforms. [Like Apple TV integration do](https://github.com/Drafteed/core/blob/braviatv-remote/homeassistant/components/apple_tv/__init__.py).

Currently i stuck. If you has the desire and motivation, feel free to contribute ;)

**Comment by Drafteed** [comment]
Please check [this PR in core](https://github.com/home-assistant/core/pull/50845).
