### ISSUE TITLE
Cannot power on KDL55W829B

### ISSUE THREAD

**Issue by ThomasPrior** [dcnielsen90/python-bravia-tv#4]
Just wanted to echo that I'm experiencing the same difficulty powering on my KDL55W829B as mentioned in https://github.com/dcnielsen90/python-bravia-tv/issues/3

Both this integration and the custom BraviaTV-PSK component display the same behaviour:

- ```media_player.turn_on``` does not turn on the device.
- Media Control card power button does not turn on the device.
- A Wake on LAN packet does wake the device.
- ```media_player.turn_off``` turns off the device.
- Media Control card power button turns off the device.

This occurs regardless of the TV power and network state when HA is started. To my untrained eye this would indicate an issue in the https://github.com/aparraga/braviarc project that both components seem to come from, but that repository looks very dead.

Home Assistant version info:

arch | x86_64
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 4.19.0-8-amd64
python_version | 3.7.3
timezone | Europe/London
version | 0.108.3
virtualenv | true

**Comment by dcnielsen90** [comment]
Hey @ThomasPrior thanks for your feedback. I'm going to close this to issue #3 seeing as they document the same issue. If you have any more feedback on this issue please comment there. Thanks!
