### ISSUE TITLE
Error after turning off the TV

### ISSUE THREAD

**Issue by bieniu** [dcnielsen90/python-bravia-tv#5]
A while after turning off the TV I have in the log this error:
```
2020-04-14 23:09:47 ERROR (SyncWorker_9) [bravia_tv.braviarc] JSON request error:{
    "error": [
        404,
        "Not Found"
    ]
}
```

**Comment by robo667** [comment]
I have the same error 
![61011D4F-04BC-4609-ABD0-3C17CBB3E9E2](https://user-images.githubusercontent.com/59558675/79311686-19ed5a80-7efe-11ea-9428-6a9ea1ed32cd.jpeg)

**Comment by andriej** [comment]
Same error (which is not really an error, it's just TV turning off) here - latest 0.108.

**Comment by dcnielsen90** [comment]
The latest commits should be enough to fix this. I'm also in the middle of drafting a PR for HA that should finally fix this once and for all. It should also address all the power issues (minus issue #3 --I'm still looking into that) I'll try to get it in by this weekend.

**Comment by bieniu** [comment]
I can confirm that update `bravia_tv` to 1.0.2 fixed this issue.
